jms_security_extra:
    secure_all_services: false
    expressions: true
   
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER, ROLE_EDITOR
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:       true 
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/blog/, role: ROLE_ADMIN }
   
   
#security:
#    acl:
#        connection: default
#    
#    access_control:
#        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
#        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/resetting, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/blog/, roles: ROLE_USER }
#        - { path: ^/admin/, roles: ROLE_ADMIN }
#        
#    encoders:
#        Symfony\Component\Security\Core\User\User: plaintext
#        Serialken\UserBundle\Entity\User:   sha512
#    
#    role_hierarchy:
#        ROLE_ADMIN:       [ROLE_AUTEUR, ROLE_MODERATEUR, ROLE_USER]
#        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
#
#    providers:
#        fos_userbundle:
#            id: fos_user.user_provider.username
#        
#
#    firewalls:
#        dev:
#            pattern:  ^/(_(profiler|wdt)|css|images|js)/
#            security: false      
#        main_login:
#            pattern:    ^/(login$|login_check|register|resetting) #jautorise les anonyme sur ces pages ,logique
#            anonymous:  true    
#        # Firewall pour le reste du site
#        main:
#            pattern:    ^/blog
#            anonymous:  true
#            form_login:
#                provider:   fos_userbundle
#                login_path: fos_user_security_login
#                check_path: fos_user_security_check
#            logout: true
#            remember_me:
#                key:    %secret%    #c'est un param de param.yml