
serialkenblog_accueil:
    path:     /{page}
    defaults: { _controller: SerialkenBlogBundle:Blog:index, page: 1 }
    requirements:
        page: \d*

serialkenblog_voir:
    path:     /article/{id}
    defaults: { _controller: SerialkenBlogBundle:Blog:voir }
    requirements:
        id: \d+

serialkenblog_ajouter:
    path:     /ajouter
    defaults: { _controller: SerialkenBlogBundle:Blog:ajouter }
    
serialkenblog_ajouter_commentaire:
    path:     /article/commentaire/ajouter/{id}
    defaults: { _controller: SerialkenBlogBundle:Blog:ajouterCommentaire }
    
serialkenblog_supprimer_commentaire:
    path:     /article/commentaire/supprimer/{id}
    defaults: { _controller: SerialkenBlogBundle:Blog:supprimerCommentaire }

serialkenblog_modifier:
    path:     /modifier/{id}
    defaults: { _controller: SerialkenBlogBundle:Blog:modifier }
    requirements:
         id: \d+

serialkenblog_supprimer:
    path:     /supprimer/{id}
    defaults: { _controller: SerialkenBlogBundle:Blog:supprimer }
    requirements:
         id: \d+
       
serialkenblog_load:
    path:       /load
    defaults:   { _controller: SerialkenBlogBundle:Blog:load }

serialkenblog_voir_slug:
    path:     /article/{annee}/{slug}.{_format}
    defaults: { _controller: SerialkenBlogBundle:Blog:voirSlug }
    requirements:
        annee: \d{4}
        format: html|xml
        
