<?php

namespace Serialken\BlogBundle\Repository;

use Doctrine\ORM\EntityRepository;



/**
 * ArticleCompetenceRepository
 *
 * This class was generated by me 
 * repository methods below.
 */
class ArticleCompetenceRepository extends EntityRepository
{
    public function findbyArticle($id)
    {
         //die(var_dump($this->findBy(array('' => 'expert'))));
        $this->createQueryBuilder('a')
                ->andWhere('a.article = :id')
                ->setParameter('id', $id)
                ->getQuery()
                ->getResult();
//                add('where', 'article_id = :id')->setParameter('id', $id)->getQuery()->getresult()));
       //return $this->_em->createQuery('SELECT a.niveau FROM SerialkenBlogBundle:ArticleCompetence a WHERE a.artilcle_id = :id ')->setParameter('id', $id);
//               ->add('select', '*')
//               ->add('from', 'articlecompetence')
//               ->where('article_id = :id')
//               ->setParameter('id', $id);
    }
}