<?php

namespace EnhancedProxy6e27d075_d0ed5d4a8272311479604cec3d1a5fdeff105f17\__CG__\Serialken\BlogBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class BlogController__JMSInjector
{
    public static function inject($container) {
        require_once 'C:/Users/yannick.dieng/Workspace/Symfony/app/cache/dev/jms_diextra/proxies/EnhancedProxy6e27d075_d0ed5d4a8272311479604cec3d1a5fdeff105f17-__CG__-Serialken-BlogBundle-Controller-BlogController.php';
        $b = new \JMS\AopBundle\Aop\InterceptorLoader($container, array('Serialken\\BlogBundle\\Controller\\BlogController' => array('supprimerAction' => array(0 => 'security.access.method_interceptor'), 'modifierAction' => array(0 => 'security.access.method_interceptor'))));
        $instance = new \EnhancedProxy6e27d075_7e5bed84da38a5a625ea432bf81e75bb6baa7985\__CG__\Serialken\BlogBundle\Controller\BlogController();
        $instance->__CGInterception__setLoader($b);
        return $instance;
    }
}
