<?php

namespace Serialken\BlogBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class BlogController__JMSInjector
{
    public static function inject($container) {
        require_once 'C:/Users/yannick.dieng/Workspace/Symfony/app/cache/dev/jms_diextra/proxies/Serialken-BlogBundle-Controller-BlogController.php';
        $a = new \JMS\AopBundle\Aop\InterceptorLoader($container, array('Serialken\\BlogBundle\\Controller\\BlogController' => array('modifierAction' => array(0 => 'security.access.method_interceptor'), 'supprimerAction' => array(0 => 'security.access.method_interceptor'))));
        $instance = new \EnhancedProxydbc1d732_d0ed5d4a8272311479604cec3d1a5fdeff105f17\__CG__\Serialken\BlogBundle\Controller\BlogController();
        $instance->__CGInterception__setLoader($a);
        return $instance;
    }
}
